insert into Libraries (Name, Address, Phone, OpenFrom, OpenUntil) values ('Bibliotekele', '979 Erie Lane', '246-566-7264', '21:35', '2:27');

insert into Authors (FirstName, LastName) values ('Carmon', 'Pabel');
insert into Authors ( FirstName, LastName) values ('Justina', 'Bugdale');
insert into Authors ( FirstName, LastName) values ('Rebeka', 'Domerq');
insert into Authors ( FirstName, LastName) values ('Davin', 'Noone');
insert into Authors ( FirstName, LastName) values ('Delly', 'Bownass');
insert into Authors ( FirstName, LastName) values ('Layne', 'Bedding');
insert into Authors ( FirstName, LastName) values ('Torrey', 'Tireman');
insert into Authors ( FirstName, LastName) values ('Barbee', 'Viste');
insert into Authors ( FirstName, LastName) values ('Greg', 'Scollan');
insert into Authors ( FirstName, LastName) values ('Kylila', 'Coulbeck');

insert into Computers ( CPU, GPU, Monitor, LibraryId) values ('AMD Ryzen 5 3400G', 'AMD Radeon RX 6800', 'BenQ PD3200U', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ('AMD Ryzen 5 3400G', 'Nvidia GeForce RTX 3060 Ti', 'BenQ PD3200U', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ('Intel Core i5-10600K', 'Zotac GeForce RTX 2060 Super Mini', 'LG UltraGear 38GN950', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ('AMD Ryzen 5 3400G', 'Nvidia GeForce RTX 3060 Ti', 'LG UltraGear 38GN950', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ('AMD Ryzen 5 3400G', 'AMD Radeon RX 6800', 'LG UltraGear 38GN950', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ('Intel Core i7-10700K', 'Nvidia GeForce RTX 3060 Ti', 'BenQ PD3200U', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ('Intel Core i5-10600K', 'Nvidia GeForce RTX 3060 Ti', 'BenQ PD3200U', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ('AMD Ryzen 5 3400G', 'AMD Radeon RX 6800', 'LG UltraGear 38GN950', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ('AMD Ryzen 5 3400G', 'Zotac GeForce RTX 2060 Super Mini', 'Asus ROG Swift PG27UQ', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'Intel Core i7-10700K', 'Zotac GeForce RTX 2060 Super Mini', 'Asus ROG Swift PG27UQ', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'AMD Ryzen 5 3400G', 'Nvidia GeForce RTX 3060 Ti', 'BenQ PD3200U', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'Intel Core i7-10700K', 'Nvidia GeForce RTX 3060 Ti', 'LG UltraGear 38GN950', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'Intel Core i5-10600K', 'Zotac GeForce RTX 2060 Super Mini', 'LG UltraGear 38GN950', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'AMD Ryzen 5 3600X', 'Nvidia GeForce RTX 3060 Ti', 'LG UltraGear 38GN950', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'Intel Core i5-10600K', 'Zotac GeForce RTX 2060 Super Mini', 'LG UltraGear 38GN950', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'AMD Ryzen 5 3600X', 'Nvidia GeForce RTX 3060 Ti', 'BenQ PD3200U', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'Intel Core i5-10600K', 'Nvidia GeForce RTX 3060 Ti', 'Asus ROG Swift PG27UQ', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'Intel Core i5-10600K', 'Nvidia GeForce RTX 3060 Ti', 'BenQ PD3200U', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'AMD Ryzen 5 3600X', 'Zotac GeForce RTX 2060 Super Mini', 'Asus ROG Swift PG27UQ', 1);
insert into Computers ( CPU, GPU, Monitor, LibraryId) values ( 'Intel Core i7-10700K', 'AMD Radeon RX 6800', 'BenQ PD3200U', 1);

insert into Publishers ( Name, Address, Email, Password) values ('Lynch-Kautzer', '7328 Manitowish Parkway', 'yhalewood0@desdev.cn', 'framework');
insert into Publishers ( Name, Address, Email, Password) values ('Mitchell, McGlynn and White', '11173 Village Plaza', 'cdaley1@slideshare.net', 'Focused');
insert into Publishers ( Name, Address, Email, Password) values ('Ernser LLC', '5 Browning Crossing', 'lwestell2@discuz.net', 'zero defect');
insert into Publishers ( Name, Address, Email, Password) values ('Hermiston, Altenwerth and Sipes', '0352 Rieder Crossing', 'wmosedall3@google.co.uk', 'Managed');
insert into Publishers ( Name, Address, Email, Password) values ('Beer, Rodriguez and Herman', '506 Spaight Way', 'fbraunds4@miibeian.gov.cn', 'leverage');
insert into Publishers ( Name, Address, Email, Password) values ('Lockman, Waters and Stehr', '976 Columbus Alley', 'gquipp5@fastcompany.com', 'encompassing');
insert into Publishers ( Name, Address, Email, Password) values ('Kirlin, Kub and Mertz', '2915 Quincy Road', 'aposten6@w3.org', 'Compatible');
insert into Publishers ( Name, Address, Email, Password) values ('Heller-Kutch', '51033 Jackson Alley', 'dnanni7@g.co', 'methodology');
insert into Publishers ( Name, Address, Email, Password) values ('Walker, Kreiger and Hyatt', '57 Harper Park', 'tsutherden8@t-online.de', 'methodical');
insert into Publishers ( Name, Address, Email, Password) values ( 'Shields, Pfeffer and Hermann', '7 Longview Hill', 'ssainz9@phoca.cz', 'contextually-based');

insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values (1, 10, 10, 'Special Day, A (Giornata particolare, Una)', 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', 1911, 'Paraguay', 'Kashmiri', '966463975-3', '3/19/1963', 415, 23, 23, 3, 1);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values (1, 7, 8, 'Electile Dysfunction', 'eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in', 2004, 'Indonesia', 'Somali', '605101036-X', '7/9/1937', 346, 8, 42, 2, 3);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values (1, 4, 8, 'Amour fou, L''', 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit', 1995, 'Palestinian Territory', 'Hungarian', '190413397-5', '5/4/1982', 234, 19, 22, 1, 2);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values (1, 4, 1, 'American Pie Presents: The Book of Love (American Pie 7: The Book of Love)', 'nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a', 1965, 'Myanmar', 'Northern Sotho', '036430521-5', '5/13/1919', 397, 5, 27, 6, 2);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values (1, 1, 2, 'Children of the Decree (Das Experiment 770 - Gebären auf Befehl)', 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a', 2009, 'Vietnam', 'Dutch', '863929432-1', '9/26/1979', 371, 16, 7, 7, 1);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values (1, 3, 8, 'Courage Under Fire', 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 1918, 'Vietnam', 'New Zealand Sign Language', '312497159-0', '7/18/1936', 115, 10, 12, 7, 3);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values (1, 6, 2, 'Magic Hunter (Büvös vadász)', 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 1955, 'Indonesia', 'Māori', '799033546-8', '2/3/2008', 255, 10, 17, 2, 1);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values (1, 2, 8, 'Everly', 'maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus', 1907, 'Thailand', 'New Zealand Sign Language', '632565862-0', '2/25/1979', 226, 6, 6, 2, 1);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values (1, 10, 6, 'Coming Down the Mountain', 'rutrum neque aenean auctor gravida sem praesent id massa id', 1901, 'Indonesia', 'Thai', '633500275-2', '11/12/1938', 162, 9, 39, 4, 1);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 6, 6, 'Che: Part One', 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', 1916, 'Indonesia', 'Northern Sotho', '509356736-1', '10/5/1939', 206, 20, 43, 7, 3);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 5, 6, 'Hell (L''enfer)', 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 1947, 'Brazil', 'Malay', '245181934-0', '12/13/1963', 394, 13, 35, 4, 3);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 5, 5, 'By the Sword', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales', 1901, 'Kyrgyzstan', 'Tamil', '813767179-X', '7/1/1928', 130, 21, 44, 2, 2);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 5, 3, 'Mists of Avalon, The', 'velit eu est congue elementum in hac habitasse platea dictumst', 1987, 'China', 'Assamese', '140267825-8', '2/14/1925', 424, 24, 46, 3, 2);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 1, 10, 'Young Visiters, The', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue', 1988, 'Brazil', 'Aymara', '704394153-9', '3/31/1935', 251, 1, 7, 2, 3);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 1, 3, '3 Backyards', 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam', 1984, 'Indonesia', 'Gagauz', '528967404-7', '7/16/1966', 366, 3, 27, 4, 3);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 4, 8, 'Thief of Damascus', 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 1975, 'Armenia', 'Belarusian', '121768901-X', '8/19/1908', 444, 22, 34, 4, 3);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 1, 1, 'Mr. Moto Takes a Chance', 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', 2020, 'China', 'Azeri', '111820765-3', '3/22/2010', 464, 17, 47, 2, 2);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 2, 10, 'I Hired a Contract Killer', 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque', 1933, 'Portugal', 'Malagasy', '698824628-2', '4/21/1953', 114, 1, 20, 5, 3);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 7, 10, 'End of the Line, The', 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', 1950, 'Albania', 'Kyrgyz', '314236309-2', '12/17/2001', 167, 9, 11, 8, 1);
insert into Books ( LibraryId, PublisherId, AuthorId, Title, Description, YearWritten, Country, Language, ISBN, ReleaseDate, PageCount, MinAge, Price, GenreId, ConditionId) values ( 1, 8, 7, 'Domestic Disturbance', 'imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium', 2020, 'France', 'Azeri', '818542211-7', '9/30/1966', 352, 11, 26, 5, 1);

insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Ira', 'Waple', '85-705-5292', 916, 'iwaple0@whitehouse.gov', 'password', 2, NULL, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Elfie', 'Skingle', '30-768-3657', 1466, 'eskingle1@army.mil', 'password', 1, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Melinda', 'Bohea', '81-399-0243', 806, 'mbohea2@smugmug.com', 'password', 2, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Alayne', 'Deave', '89-582-1385', 799, 'adeave3@paypal.com', 'password', 2, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Herb', 'Dobrowolski', '43-892-0144', 508, 'hdobrowolski4@toplist.cz', 'password', 2, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Berkley', 'Barok', '45-425-4414', 1078, 'bbarok5@stanford.edu', 'password', 1, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Sidoney', 'Rannie', '68-390-4220', 702, 'srannie6@stanford.edu', 'password', 2, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Ammamaria', 'Pietsma', '08-811-0716', 840, 'apietsma7@marriott.com', 'password', 2, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Leoine', 'Kittredge', '37-717-1056', 670, 'lkittredge8@cloudflare.com', 'password', 1, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Kameko', 'Keys', '48-644-1036', 645, 'kkeys9@ycombinator.com', 'password', 2, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Richard', 'Le Marquand', '31-142-7843', 1331, 'rlemarquanda@goo.gl', 'password', 1, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Tanner', 'Wilfling', '18-029-4338', 873, 'twilflingb@senate.gov', 'password', 2, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Ring', 'Doumic', '57-704-2846', 1160, 'rdoumicc@ycombinator.com', 'password', 2, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Barbette', 'Demageard', '94-858-2909', 655, 'bdemageardd@domainmarket.com', 'password', 1, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Eugenie', 'Hellwich', '66-054-0297', 1489, 'ehellwiche@naver.com', 'password', 1, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Phaidra', 'Swansbury', '13-005-6480', 1323, 'pswansburyf@reddit.com', 'password', 1, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Pen', 'Gossop', '12-263-1431', 1052, 'pgossopg@psu.edu', 'password', 1, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Aveline', 'Meale', '46-419-5931', 1171, 'amealeh@yellowbook.com', 'password', 2, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Christyna', 'Vowles', '96-862-7460', 557, 'cvowlesi@reverbnation.com', 'password', 1, 1, 1);
insert into Employees (FirstName, LastName, PersonalCode, Salary, Email, Password, Duty, ReportsTo, EmployedAt) values ('Natividad', 'Beran', '82-668-2383', 1283, 'nberanj@yolasite.com', 'password', 2, 1, 1);

insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (9690, 483, '12/23/2019', '11/17/2020', 1, 1, 2, 8);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (13600, 352, '7/12/2021', '3/2/2020', 2, 1, 10, 4);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (8766, 511, '5/18/2021', '3/23/2021', 3, 1, 5, 4);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (11519, 128, '7/10/2020', '7/26/2020', 2, 1, 6, 1);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (10331, 462, '1/5/2021', '2/4/2021', 1, 1, 10, 2);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (11245, 938, '5/12/2020', '7/20/2020', 3, 1, 4, 5);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (6133, 666, '12/26/2019', '11/12/2021', 2, 1, 9, 1);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (7273, 161, '12/1/2020', '5/31/2020', 1, 1, 5, 7);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (13422, 673, '7/17/2020', '3/14/2021', 2, 1, 1, 4);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (10624, 405, '1/26/2020', '1/29/2021', 1, 1, 4, 10);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (10398, 891, '5/19/2020', '11/10/2020', 3, 1, 5, 10);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (9658, 934, '7/21/2021', '11/29/2020', 1, 1, 6, 7);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (7699, 685, '8/21/2020', '8/1/2021', 2, 1, 5, 7);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (12162, 641, '2/22/2021', '10/3/2021', 2, 1, 9, 9);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (12254, 993, '10/26/2020', '6/6/2021', 1, 1, 4, 2);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (9744, 130, '5/22/2020', '3/3/2020', 1, 1, 9, 7);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (7486, 214, '11/9/2021', '7/4/2020', 3, 1, 6, 9);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (12708, 277, '4/5/2020', '6/11/2020', 3, 1, 6, 4);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (10418, 294, '2/26/2021', '7/2/2021', 1, 1, 1, 7);
insert into Offers (Price, Amount, StartDate, EndDate, StatusId, LibraryId, PublisherId, BookId) values (13616, 256, '10/15/2020', '2/28/2020', 1, 1, 7, 7);

insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Deb', 'Sutter', '0031-2293', 'dsutter0@cocolog-nifty.com', 'password', 1, '9/18/1961');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Franky', 'Tottman', '53808-0662', 'ftottman1@printfriendly.com', 'password', 1, '10/15/1969');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Blaire', 'Spelling', '54365-400', 'bspelling2@sohu.com', 'password', 1, '6/2/1969');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Keefer', 'Delves', '42858-103', 'kdelves3@indiegogo.com', 'password', 1, '6/23/1982');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Joyann', 'Wychard', '63629-4207', 'jwychard4@alibaba.com', 'password', 1, '12/1/1996');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Loraine', 'Joisce', '40046-0043', 'ljoisce5@miitbeian.gov.cn', 'password', 1, '12/30/1959');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Henri', 'Tatam', '61715-085', 'htatam6@timesonline.co.uk', 'password', 1, '4/26/1954');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Hazel', 'Juza', '0904-5068', 'hjuza7@amazon.co.jp', 'password', 1, '5/28/1971');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Isabel', 'Sigsworth', '0591-3546', 'isigsworth8@ihg.com', 'password', 1, '9/29/1996');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Mignon', 'Kalinsky', '49643-010', 'mkalinsky9@arizona.edu', 'password', 1, '5/19/1951');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Franky', 'Collinge', '10544-210', 'fcollingea@samsung.com', 'password', 1, '4/6/1971');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Dena', 'Kurth', '0407-1413', 'dkurthb@constantcontact.com', 'password', 1, '2/1/1991');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Zara', 'Hyde', '63539-012', 'zhydec@vinaora.com', 'password', 1, '2/12/1976');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Brandon', 'O''Hear', '0268-6773', 'boheard@baidu.com', 'password', 1, '3/17/1981');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Emanuele', 'Calverd', '43857-0160', 'ecalverde@adobe.com', 'password', 1, '4/30/1989');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Evita', 'Leblanc', '63972-009', 'eleblancf@wix.com', 'password', 1, '12/26/1992');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Nonah', 'Kale', '52125-909', 'nkaleg@globo.com', 'password', 1, '8/21/1983');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Jarrett', 'Van der Spohr', '67938-0824', 'jvanderspohrh@marketwatch.com', 'password', 1, '6/5/1964');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Veradis', 'Verring', '58118-0168', 'vverringi@acquirethisname.com', 'password', 1, '12/13/1951');
insert into Users (FirstName, LastName, PersonalCode, Email, Password, IsActive, Birthday) values ('Darelle', 'Dautry', '0409-7107', 'ddautryj@ucoz.com', 'password', 1, '8/27/1974');

insert into UserLibraries (UserId, LibraryId) values (1, 1);
insert into UserLibraries (UserId, LibraryId) values (2, 1);
insert into UserLibraries (UserId, LibraryId) values (3, 1);
insert into UserLibraries (UserId, LibraryId) values (4, 1);
insert into UserLibraries (UserId, LibraryId) values (5, 1);
insert into UserLibraries (UserId, LibraryId) values (6, 1);
insert into UserLibraries (UserId, LibraryId) values (7, 1);
insert into UserLibraries (UserId, LibraryId) values (8, 1);
insert into UserLibraries (UserId, LibraryId) values (9, 1);
insert into UserLibraries (UserId, LibraryId) values (10, 1);
insert into UserLibraries (UserId, LibraryId) values (11, 1);
insert into UserLibraries (UserId, LibraryId) values (12, 1);
insert into UserLibraries (UserId, LibraryId) values (13, 1);
insert into UserLibraries (UserId, LibraryId) values (14, 1);
insert into UserLibraries (UserId, LibraryId) values (15, 1);
insert into UserLibraries (UserId, LibraryId) values (16, 1);
insert into UserLibraries (UserId, LibraryId) values (17, 1);
insert into UserLibraries (UserId, LibraryId) values (18, 1);
insert into UserLibraries (UserId, LibraryId) values (19, 1);
insert into UserLibraries (UserId, LibraryId) values (20, 1);